name: Deploy to VPS with Debug

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug SSH Key
        run: |
          echo "Checking key length"
          echo "${{ secrets.VPS_KEY }}" | wc -l
          echo "First 2 lines of key:"
          echo "${{ secrets.VPS_KEY }}" | head -n 2
          echo "Last 2 lines of key:"
          echo "${{ secrets.VPS_KEY }}" | tail -n 2

      - name: Test SSH connectivity
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@147.93.114.66 "echo SSH connection successful"
      
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: 147.93.114.66
          username: root
          port: 22
          key: ${{ secrets.VPS_KEY }}
          script: |
            echo "SSH connection verified"
            cd /var/www/solidcore-engineering-frontend
            git reset --hard
            git pull origin main
            npm install --production
            npm run build
            pm2 restart solidcore-frontend
