name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: 147.93.114.66
          username: root
          key: ${{ secrets.VPS_KEY }}
          port: 22
          script: |
            cd /var/www/solidcore-engineering-frontend
            git reset --hard
            git pull origin main
            npm install --production
            npm run build
            pm2 restart solidcore-frontend
